PACTOS = {
    'XX': 'Chile Vamos',
    'XZ': 'Ecologistas e Independientes',
    'XS': 'Frente Amplio',
    'YA': 'Humanicemos Chile',
    'U': 'Igualdad para Chile',
    'IND': 'Independiente fuera de pacto',
    'YC': 'Independientes Cristianos',
    'ZR': 'Partido de Trabajadores Revolucionarios',
    'WG': 'Partido Nacional Ciudadano',
    'ZB': 'Partido Unión Patriótica',
    'ZV': 'Por Dignidad Regional',
    'ZX': 'Regionalistas Verdes',
    'XO': 'Republicanos',
    'YN': 'Unidad Constituyente',
    'LPB': 'La Lista del Pueblo Distrito 14',
    'XC': 'A Pulso, Por el Buen Vivir',
    'YQ': 'Apruebo Dignidad',
    'WK': 'Arica Siempre Arica',
    'WJ': 'Asamblea Constituyente Atacama',
    'ZW': 'Asamblea Popular Constituyente',
    'XI': 'Asamblea Popular por la Dignidad',
    'XN': 'Autonomía Social y Sindical Tarapacá',
    'F': 'Biobío Sin Partidos',
    'ZF': 'Cabildos Autoconvocados',
    'W': 'Chile Independiente',
    'YX': 'Ciudadanos Cristianos',
    'YO': 'Comunidad Independiente de Maule',
    'XL': 'Comunidad Independiente Ven Seremos',
    'ZI': 'Coordinadora Social de Magallanes',
    'YZ': 'Corrientes Independientes',
    'ZM': 'Decisión Ciudadana',
    'J': 'Elige La Lista del Pueblo',
    'XF': 'Energía Independiente',
    'XJ': 'Fuerza Social de Ñuble, La Lista del Pueblo',
    'H': 'Independientes Como Tú',
    'ZY': 'Independientes con Chile',
    'A': 'Independientes de Tarapacá',
    'YF': 'Independientes de Ñuble por la Nueva Constitución',
    'WI': 'Independientes del Apruebo Región Coquimbo',
    'I': 'Independientes del Biobío por una Nueva Constitución',
    'L': 'Independientes del Norte Grande por una Nueva Constitución',
    'S': 'Independientes Distrito 6 + Lista del Pueblo',
    'ZA': 'Independientes Nueva Constitución',
    'ZT': 'Independientes por la Nueva Constitución',
    'YV': 'Independientes por una Nueva Constitución',
    'YS': 'Independientes Sin Padrinos',
    'YU': 'Independientes y Movimientos Sociales del Apruebo',
    'G': 'Insulares e Independientes',
    'ZN': 'La Lista del Pueblo',
    'YP': 'La Lista del Pueblo 100% Independientes',
    'YL': 'La Lista del Pueblo Distrito 12',
    'N': 'La Lista del Pueblo Distrito 9',
    'ZD': 'La Lista del Pueblo Maule Sur',
    'YB': 'Lista del Apruebo',
    'WD': 'Lista del Pueblo - Movimiento Territorial Constituyente',
    'Q': 'Lista del Pueblo Transformando desde el Willi',
    'XD': 'Lista del Pueblo-Ríos Independientes',
    'YI': 'Lista Independiente Parto Social',
    'XH': 'Lista por la Justicia Social',
    'YT': 'Lista Social Poder Constituyente a Toda Costa',
    'XR': 'Magallánicos No Neutrales',
    'ZZ': 'Movimiento Independientes del Norte',
    'XT': 'Movimiento Social Constituyente / La Lista del Pueblo',
    'ZE': 'Movimiento Social La Lista del Pueblo',
    'ZL': 'Movimiento Sociales: Unidad de Independientes',
    'YK': 'Movimientos Sociales Independientes',
    'ZH': 'Movimientos Sociales Plurinacionales e Independientes',
    'P': 'Movimientos Sociales y Autónomos',
    'XB': 'Nobles Hijxos de Tarapacá',
    'ZQ': 'Nuestras Voces',
    'ZK': 'Organizaciones Sociales y Territoriales del Wallmapu',
    'XA': 'Partido Ecologista Verde',
    'XG': 'Partido Humanista',
    'YD': 'Patagonia Somos Todos',
    'E': 'Pueblo Unido Tarapacá',
    'XM': 'Regionalismo Ciudadano Independiente',
    'YE': 'República de los Independientes de Magallanes',
    'XV': 'Sexta Unida',
    'D': 'Soberanía Ciudadana',
    'WE': 'Súmate Ahora',
    'XP': 'Vamos por Chile',
    'T': 'Voces Constituyentes',
    'XU': 'Unidos por la Dignidad',
    'K': 'Unidad por el Apruebo',
    'WB': 'Independientes por la Región de Coquimbo',
    'XY': 'Dignidad Ahora',
    'YG': 'Nuevo Tiempo',
    'XE': 'Ciudadanos Independientes',
    'M': 'Chile Digno Verde y Soberano',
    'AI-XV': 'Aimara - Arica y Parinacota',
    'AI-I': 'Aimara - Tarapacá',
    'CH-II': 'Chango - Antofagasta',
    'CH-III': 'Chango - Atacama',
    'CH-IV': 'Chango - Coquimbo',
    'CO-III': 'Colla - Atacama',
    'DG-III': 'Diaguita - Atacama',
    'DG-IV': 'Diaguita - Coquimbo',
    'KW-XII': 'Kawashkar - Magallanes',
    'AT-II': 'Atacameño - Antofagasta',
    'MP-RM': 'Mapuche - Metropolitana',
    'MP-VIII': 'Mapuche - Biobío',
    'MP-IX': 'Mapuche - Araucanía',
    'MP-XIV': 'Mapuche - Los Ríos',
    'MP-X': 'Mapuche - Los Lagos',
    'MP-XI': 'Mapuche - Aysén',
    'QC-I': 'Quechua - Tarapacá',
    'QC-II': 'Quechua - Antofagasta',
    'RN-V': 'Rapa Nui - Valparaíso',
    'YG-XII': 'Yagán - Magallanes'}


DISTRITOS = [
    {"c": 6001, "d": "DISTRITO 1"}, {"c": 6002, "d": "DISTRITO 2"}, {"c": 6003, "d": "DISTRITO 3"},
    {"c": 6004, "d": "DISTRITO 4"}, {"c": 6005, "d": "DISTRITO 5"}, {"c": 6006, "d": "DISTRITO 6"},
    {"c": 6007, "d": "DISTRITO 7"}, {"c": 6008, "d": "DISTRITO 8"}, {"c": 6009, "d": "DISTRITO 9"},
    {"c": 6010, "d": "DISTRITO 10"}, {"c": 6011, "d": "DISTRITO 11"}, {"c": 6012, "d": "DISTRITO 12"},
    {"c": 6013, "d": "DISTRITO 13"}, {"c": 6014, "d": "DISTRITO 14"}, {"c": 6015, "d": "DISTRITO 15"},
    {"c": 6016, "d": "DISTRITO 16"}, {"c": 6017, "d": "DISTRITO 17"}, {"c": 6018, "d": "DISTRITO 18"},
    {"c": 6019, "d": "DISTRITO 19"}, {"c": 6020, "d": "DISTRITO 20"}, {"c": 6021, "d": "DISTRITO 21"},
    {"c": 6022, "d": "DISTRITO 22"}, {"c": 6023, "d": "DISTRITO 23"}, {"c": 6024, "d": "DISTRITO 24"},
    {"c": 6025, "d": "DISTRITO 25"}, {"c": 6026, "d": "DISTRITO 26"}, {"c": 6027, "d": "DISTRITO 27"},
    {"c": 6028, "d": "DISTRITO 28"}]